"""add embedding_id to chunks

Revision ID: e392a01fa753
Revises: 0001
Create Date: 2026-04-26 16:25:01.440104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e392a01fa753'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'embedding_id',
               existing_type=sa.TEXT(),
               comment='Reference ID in the FAISS index for this chunk',
               existing_nullable=True)
    op.create_foreign_key(None, 'chunks', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.alter_column('chunks', 'embedding_id',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Reference ID in the FAISS index for this chunk',
               existing_nullable=True)
    # ### end Alembic commands ###
